### ISSUE TITLE
🛑 makedeb Package Repository is down

### ISSUE THREAD

**Issue by kavplex** [makedeb/status#74] opened 2022-11-15 01:59 UTC
In [`78ea5a0`](https://github.com/makedeb/status/commit/78ea5a0b1c6fcce97aceffe4b74663262b8ddc17
), makedeb Package Repository (https://mpr.makedeb.org) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by hwittenborn** [comment] 2022-11-15 03:00
The cause of this issue has been confirmed and a fix has been implemented. Another update will be posted shortly.

**Closed** 2022-11-15 03:01 UTC
Labels: status, makedeb-package-repository

**Comment by hwittenborn** [comment] 2023-02-13 14:11
Deleting because this was due to nightly backups.
